services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - radarr-config:/config
      - /home/user/media/movies:/movies
      - /home/user/media/downloads:/downloads

volumes:
  radarr-config:
