services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: always
    ports:
      - "8686:8686"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - lidarr-config:/config
      - /home/user/media/music:/music
      - /home/user/media/downloads:/downloads

volumes:
  lidarr-config:
